import { app__modules__cdr__schemas_cdr__ProductComplete } from "@/api";

export const products: app__modules__cdr__schemas_cdr__ProductComplete[] = [
  {
    name_fr: "Produit 1",
    name_en: "Product 1",
    description_fr: "Description du produit 1",
    description_en: "Product 1 description",
    available_online: true,
    id: "1",
    seller_id: "1",
    variants: [
      {
        id: "1",
        price: 10,
        product_id: "1",
        name_fr: "Variante 1",
        name_en: "Variant 1",
        enabled: false,
        unique: false,
      },
      {
        id: "2",
        price: 20,
        product_id: "1",
        name_en: "Variant 2",
        name_fr: "Variante 2",
        enabled: true,
        unique: false,
      },
      {
        id: "3",
        price: 30,
        product_id: "1",
        name_en: "Variant 3",
        name_fr: "Variante 3",
        enabled: true,
        unique: false,
      },
    ],
  },
  {
    name_fr: "Produit 2",
    name_en: "Product 2",
    description_fr: "Description du produit 2",
    description_en: "Product 2 description",
    available_online: true,
    id: "2",
    seller_id: "1",
    variants: [
      {
        id: "1",
        price: 10,
        product_id: "1",
        name_fr: "Variante 1",
        name_en: "Variant 1",
        enabled: false,
        unique: false,
      },
      {
        id: "2",
        price: 20,
        product_id: "1",
        name_en: "Variant 2",
        name_fr: "Variante 2",
        enabled: true,
        unique: false,
      },
    ],
  },
  {
    name_fr: "Produit 3",
    name_en: "Product 3",
    description_fr: "Description du produit 3",
    description_en: "Product 3 description",
    available_online: true,
    id: "3",
    seller_id: "1",
    variants: [
      {
        id: "1",
        price: 10,
        product_id: "1",
        name_fr: "Variante 1",
        name_en: "Variant 1",
        enabled: false,
        unique: false,
      },
      {
        id: "2",
        price: 20,
        product_id: "1",
        name_en: "Variant 2",
        name_fr: "Variante 2",
        enabled: true,
        unique: false,
      },
      {
        id: "3",
        price: 30,
        product_id: "1",
        name_en: "Variant 3",
        name_fr: "Variante 3",
        enabled: true,
        unique: false,
      },
    ],
  },
  {
    name_fr: "Produit 4",
    name_en: "Product 4",
    description_fr: "Description du produit 4",
    description_en: "Product 4 description",
    available_online: true,
    id: "4",
    seller_id: "1",
    variants: [
      {
        id: "1",
        price: 10,
        product_id: "1",
        name_fr: "Variante 1",
        name_en: "Variant 1",
        enabled: false,
        unique: false,
      },
      {
        id: "2",
        price: 20,
        product_id: "1",
        name_en: "Variant 2",
        name_fr: "Variante 2",
        enabled: true,
        unique: false,
      },
    ],
  },
  {
    name_fr: "Produit 5",
    name_en: "Product 5",
    description_fr: "Description du produit 5",
    description_en: "Product 5 description",
    available_online: true,
    id: "5",
    seller_id: "1",
    variants: [
      {
        id: "1",
        price: 10,
        product_id: "1",
        name_fr: "Variante 1",
        name_en: "Variant 1",
        enabled: false,
        unique: false,
      },
      {
        id: "2",
        price: 20,
        product_id: "1",
        name_en: "Variant 2",
        name_fr: "Variante 2",
        enabled: true,
        unique: false,
      },
      {
        id: "3",
        price: 30,
        product_id: "1",
        name_en: "Variant 3",
        name_fr: "Variante 3",
        enabled: true,
        unique: false,
      },
    ],
  },
];
